name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: checkout Repo
        uses: actions/checkout@v7
      - name: Setup dotnet
        uses: actions/setup-dotnet@v6
        with:
          dotnet-version: 10.0.x

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --configuration Release
